#!/usr/bin/python3

import sys
import math
import ctypes

lib = ctypes.CDLL("./liball.so")
factor_c = lib.factor
get_line = lib.g_g_fun
lib.g_g_fun.argtypes = [ctypes.c_int, ctypes.c_char_p]
lib.g_g_fun.restype = None
file_ = open(sys.argv[1], "r")
li = file_.readlines()
file_.close()

for x in range(len(li)):
    temp = int(li[x])
    i = 2
    while i <= temp:
        if i > 50:
            if len(li[x]) <= 18:
                filename = sys.argv[1].encode('utf-8')
                get_line(x, filename)
            break;
        if (temp % i)  == 0:
            res = temp / i
            print("{}={}*{}".format(temp, res, i))
            break
        else:
            i += 1
