#!/usr/bin/python3

import sys

def fun(x, i):
        print(i)
        if (x % i)  == 0 or i > x:
                return (i)
        else:
                return fun(x, i + 1)

file_ = open(sys.argv[1], "r")
li = file_.readlines()

for x in range(len(li)):
        temp = int(li[x])
        i = 2
        i = fun(temp, i)
        z = int(temp / i)
        print("{}={}*{}".format(temp, z, i))
